### ISSUE TITLE
Running the code error: Gulp error

### ISSUE THREAD

**Issue by tesYolan** [tesYolan/mediasoup-demo#1]
```
/home/tesfa/Downloads/node-v6.10.2-linux-x64/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /home/tesfa/Downloads/node-v6.10.2-linux-x64/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

```

**Comment by tesYolan** [comment]
Fix is: 
```
    npm rm --global gulp
    npm install --global gulp-cli
```
It seems there issue with gulp installed globally.
